### ISSUE TITLE
Proposal: always compress folders before deploy

### ISSUE THREAD

**Issue by vvo** [netlify/netlify-cli#19]
Hi, I noticed that when you use netlify deploy on a folder, it will be a lot slower than deploying that same folder as a zip file (expected).

What if the netlify-cli automatically compressed folders before sending them to netlify servers? We could use https://github.com/archiverjs/node-archiver for that.

I would like to hear your feedback on this as there may be a good reason for not compressing folders before sending over the wire.

As a first step, maybe the documentation could be explicit about the fact that folders are sent uncompressed and if you do not have an optic fiber setup then compressing to a zip before sending can be a good idea.

Thanks!

**Comment by fool** [comment]
Hi there and sorry to be so slow to respond.  We have basically stopped development on netlify-cli and are focusing on [netlifyctl](https://github.com/netlify/netlifyctl) .  So I doubt we'll add this feature, but PR's are accepted if you want to take a shot at it.

**Comment by biilmann** [comment]
In general, not compressing the folders will be faster since with this method we do incremental deploys (ie, we only ship the files that changed) whereas zip based deploys needs to send all files on each deploy.

**Comment by vvo** [comment]
I am fine with your answer, thanks
