### ISSUE TITLE
`netlify deploy` hangs on "path to deploy"

### ISSUE THREAD

**Issue by whmountains** [netlify/netlify-cli#27]
**- Do you want to request a *feature* or report a *bug*?**
Request a feature

**- What is the current behavior?**
See steps to reproduce
```shell
$ netlify deploy
? No site id specified, create a new site Yes
? Path to deploy? (current dir)
```

At this point the it becomes unresponsive and doesn't echo my typing.  ^C does nothing.  The only way to stop it is to close the terminal window.

**- If the current behavior is a bug, please provide the steps to reproduce.**
It works consistently if the `.netlify` is not present.  Deploying an existing project seems to work fine.

**- What is the expected behavior?**
The expected behavior is that it creates a new project and doesn't become unresponsive. (Duh!)

**- Please mention your node.js, and operating system version.**
Netlify v1.2.2
Node v8.1.0
Mac OS 10.12.6 Sierra

**Comment by fool** [comment]
I think this issue is actually due to some bug in Node v8.1.0 and goes away if you use Node v8.1.2 - could you give this a shot for me?

**Comment by whmountains** [comment]
Yes, that works.  Thanks a lot!
