### ISSUE TITLE
Deploy Error - netlify/lib/site.js:90

### ISSUE THREAD

**Issue by Knusper** [netlify/netlify-cli#3]
I cannot deploy anymore :-(

```
/usr/lib/node_modules/netlify-cli/node_modules/netlify/lib/site.js:90
          data.required.forEach(function(sha) { shas[sha] = true; });
              ^
TypeError: Cannot read property 'required' of null
    at /usr/lib/node_modules/netlify-cli/node_modules/netlify/lib/site.js:90:15
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/netlify-cli/node_modules/netlify/lib/client.js:286:13)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

**Comment by biilmann** [comment]
Need a few more details. The code used to do the deploy would help and the site url (you can mail that to mathias@netlify.com) so I can check our logs.

**Comment by sastraxi** [comment]
I've got the same error message--just signed up for the service and would love to deploy via cli so I can hook into our existing gitlab CI workflow. Running on windows, node v0.12.7, latest netlify-cli installed via npm.

**Comment by biilmann** [comment]
I'm looking into this, but haven't found any way to replicate it so far, neither on windows or OS X, wonder if one of you can share a repo with me or send me a zip of the folder to deploy at matt@netlify.com, then I can check if that gives me the same error...

**Comment by biilmann** [comment]
Managed to replicate the problem locally with the folder you sent, and this commit should take care of the issue.

**Comment by sastraxi** [comment]
You're awesome. Thanks, we're on the east coast so I'll take a look when i
get into work tomorrow.
