### ISSUE TITLE
Console output disappears on PowerShell + ConEmu

### ISSUE THREAD

**Issue by resir014** [netlify/netlify-cli#34]
**- Do you want to request a *feature* or report a *bug*?**

Bug.

**- What is the current behavior?**

I'm on Windows and I use ConEmu as my console emulator. Whenever I run `netlify` through ConEmu on PowerShell, the colours break to the point where no text is visible on the console unless I select a block of text. It also persists after the command is finished, even after running `cls`.

![image](https://user-images.githubusercontent.com/5663877/32666241-6341c09a-c669-11e7-9454-33f1d642122f.png)

![image](https://user-images.githubusercontent.com/5663877/32666248-677f717a-c669-11e7-9201-65301e891d61.png)

**- If the current behavior is a bug, please provide the steps to reproduce.**

* Install [ConEmu](https://conemu.github.io/).
* Run a PowerShell console through ConEmu.
* Run `netlify`.
* Text disappears.

**- What is the expected behavior?**

Normal behaviour when running through a regular `cmd`/`powershell` window:

![image](https://user-images.githubusercontent.com/5663877/32666395-dc964ff6-c669-11e7-80eb-5658db567330.png)

**- Please mention your node.js, and operating system version.**

* Node 8.9.0
* Windows 10 (x64) Build 16299

**Comment by verythorough** [comment]
Looks OK in my ConEmu/PowerShell:
![ps-netlify-cli](https://user-images.githubusercontent.com/6111186/32676099-3354515a-c60e-11e7-9b62-92db184a7f8f.png)

so we must be using different color schemes.  Here's what I have in Settings > Features > Colors:
![conemu-colors](https://user-images.githubusercontent.com/6111186/32676270-d87be724-c60e-11e7-88eb-739e8fd3a920.png)

**Comment by verythorough** [comment]
Also, one of the cool things about ConEmu is that it live updates the console window when you change the colors, so you can have the window open with the netlify-cli text, then scroll through the different color schemes (or change colors individually) until you see the text.

**Comment by resir014** [comment]
@verythorough Hmm, this is weird, tried cycling through the color schemes, nothing else worked except PowerShell (but only briefly):

![2017-11-11_11-26-24](https://user-images.githubusercontent.com/5663877/32686215-b7406376-c6d3-11e7-90a1-cbe150ef50fb.gif)

But when I switch to it, it broke again.

![2017-11-11_11-34-11](https://user-images.githubusercontent.com/5663877/32686271-4eb5c516-c6d4-11e7-9018-9d3e399ff132.gif)

![2017-11-11_11-33-00](https://user-images.githubusercontent.com/5663877/32686272-53704766-c6d4-11e7-9d16-7f21fb04b4bb.gif)

I was using the Ubuntu color scheme, with no additional configuration.

**Comment by verythorough** [comment]
Hm, that is so strange!

I'm curious—have you tried the Go-based cli tool, [netlifyctl](https://github.com/netlify/netlifyctl)? I wonder if it has the same issue. We'll be focusing future development efforts on that client, so I recommend giving it a try. (It just recently reached feature equivalence with netlify-cli, so we're in the process of updating the docs to match, but all commands described in the docs are available in netlifyctl in the same way they're available in netlify-cli.)

**Comment by resir014** [comment]
@verythorough Hey, sorry for taking too long to get back to you!

And yeah, using `netlifyctl` fixed the colours. Thanks!
