### ISSUE TITLE
deploy hangs on "Processing"

### ISSUE THREAD

**Issue by tj** [netlify/netlify-cli#36]
On a Mac and Node 8.9.3 (tried a few other major versions as well), CLI version 1.2.2, it seems to hang indefinitely but I'm not sure if it's Netlify itself or a problem with the CLI. 

Interesting note is that it does seem to eventually deploy, however the CLI still hangs showing the Processing spinner.

Thanks for the rad service!

**Comment by rybit** [comment]
take a look at the [netlifyctl project](https://github.com/netlify/netlifyctl) (it is what we're going to be supporting going forward) and if that doesn't fix it please feel free to contact support!
