### ISSUE TITLE
does not work with node 10

### ISSUE THREAD

**Issue by jcoby** [netlify/netlify-cli#40]
```node[13766]: ../src/node_contextify.cc:631:static void node::contextify::ContextifyScript::New(const FunctionCallbackInfo<v8::Value> &): Assertion `args[1]->IsString()' failed.
 1: node::Abort() [/usr/local/bin/node]
 2: node::Assert(char const* const (*) [4]) [/usr/local/bin/node]
 3: node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]```

Due to reliance on `natives` package. See nodejs bug reports https://github.com/nodejs/node/issues/20325, https://github.com/nodejs/node/issues/20281, https://github.com/nodejs/node/issues/20285

**Comment by bcomnes** [comment]
This cli is no longer supported, please switch to https://github.com/netlify/netlifyctl

**Comment by XhmikosR** [comment]
@bcomnes: you should mark the npm package as deprecated then...

**Comment by bcomnes** [comment]
Agreed, I'll look into to doing that.

**Comment by zeusdeux** [comment]
@bcomnes As a first step though, I agree that it would be super helpful to mark the npm package as deprecated and provide a link out to the new cli in the deprecation message.

**Comment by alexrussell** [comment]
Now this doesn't work in Node 10, you really had ought to update your docs to use `netlifyctl` and provide info for the "old" `netlify-cli` package as a fallback. Or at the very least make the intended deprecation and fact that you ought to use `netlifyctl` if you're on Node 10+ a lot more obvious.

**Comment by jcoby** [comment]
In addition to marking the npm package as deprecated a bigger notice in the README would be helpful as well. I had to read it several times before I noticed it included a deprecation notice.

**Comment by laggingreflex** [comment]
Might also wanna put a similar notice on the very old npm [netlify](https://www.npmjs.com/package/netlify) package which I thought was still in use after coming back to netlify after a long time. It links to the [node-client](https://github.com/netlify/node-client) github which says it's archived but redirects the user to [netlify/open-api](https://github.com/netlify/open-api/) which doesn't seem much relevant.

**Comment by singuista** [comment]
SO proud to say that one of my Junior dev's found her own solution to this. Just run these commands in sequence in the your project's directory:
rm -fr node_modules
rm -fr package-lock.json
npm cache clean --force
npm install

note: it's npm cache that's causing the biggest issues in our situation. Hope this helps

**Comment by bcomnes** [comment]
Recent development, we are revisiting plans around the Node netlify api lib and CLI.  Will follow up with more details asap, but we are thinking of resurrecting a JS/Node cli.

**Comment by leandroti7** [comment]
Thanks so much guy, you helpout me !!! # @singuista

**Comment by terrancecorley** [comment]
Any updates on this? Should I uninstall the old cli and install this new cli going forward?

**Comment by bcomnes** [comment]
Apologies for the delayed response.  

We are working on/exploring a revamped node-cli with a new architecture that will be flexible enough for some really exciting developments we have coming down the pipe.  That won't be ready for a bit, so in the meantime, I'll go ahead and do a little bit of cleanup regarding the lock files mentioned by @singuista and cut a patch release to see if that fixes some of the showstoppers on this codebase.  

Also [github.com/netlify/netlifyctl](https://github.com/netlify/netlifyctl) is a viable and working option, however I do sympathize that go tooling doesn't have the cleanest integration path that npm published tools have with most web projects that are already using npm/yarn.

Hold tight!

If you have a moment as well, I would love to hear some feedback what you want most out of the cli experience.  Trying to avoid the web UI and use the console only?  Custom deploys from private CI environments?  Advanced automation integrations?

**Comment by bcomnes** [comment]
Ok `npm install netlify-cli@latest -g`

🎉`netlify-cli@v1.2.3` 🎉

**Comment by zeusdeux** [comment]
@bcomnes so, which cli out of the two is deprecated?

**Comment by bcomnes** [comment]
This one.

**Comment by deadcoder0904** [comment]
@bcomnes Suggestion: Just make it as simple as the Now CLI or Surge CLI. No need for `netlify deploy` and all. 

Just simple command `netlify` & it will deploy current directory then ask for site name, etc.. in the terminal.

Why waste so much time on architecture when your competitors have already solved the same problem? I prefer both NOW & SURGE CLIs but I ❤️ Netlify & CLI can be a huge boon
